version: 1.2
workflows:
  - name: tree_nine
    subclass: WDL
    primaryDescriptorPath: /tree_nine.wdl
    readMePath: /README.md
    authors:
      - orcid: 0000-0003-4896-1858
    testParameterFiles:
      - /tree_nine_terra.json
      - /tree_nine_local.json