version: 1.2
workflows:
  - name: tree_nine
    subclass: WDL
    primaryDescriptorPath: /tree_nine.wdl
    readMePath: /README.md
    authors:
      - orcid: 0000-0003-4896-1858
    testParameterFiles:
      - /input_jsons/terra.json
      - /input_jsons/reroot.json
  - name: matUtils_summarize
    subclass: WDL
    primaryDescriptorPath: /summarize.wdl
    readMePath: /README.md
    authors:
      - orcid: 0000-0003-4896-1858